package com.amrut.prabhu.Prometheusintegration.infrastructure;

import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2026-03-05T01:35:51.873+05:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "TemperatureService",
                  wsdlLocation = "classpath:wsdl/temperature.wsdl",
                  targetNamespace = "http://example.com/temperature")
public class TemperatureService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://example.com/temperature", "TemperatureService");
    public static final QName TemperaturePort = new QName("http://example.com/temperature", "TemperaturePort");
    static {
        URL url = TemperatureService.class.getClassLoader().getResource("wsdl/temperature.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TemperatureService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/temperature.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TemperatureService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TemperatureService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TemperatureService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TemperatureService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TemperatureService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TemperatureService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TemperaturePortType
     */
    @WebEndpoint(name = "TemperaturePort")
    public TemperaturePortType getTemperaturePort() {
        return super.getPort(TemperaturePort, TemperaturePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TemperaturePortType
     */
    @WebEndpoint(name = "TemperaturePort")
    public TemperaturePortType getTemperaturePort(WebServiceFeature... features) {
        return super.getPort(TemperaturePort, TemperaturePortType.class, features);
    }

}
