package com.amrut.prabhu.Prometheusintegration.infrastructure;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2026-03-05T01:35:51.824+05:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://example.com/temperature", name = "TemperaturePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TemperaturePortType {

    @WebMethod(operationName = "CelsiusToFahrenheit", action = "CelsiusToFahrenheit")
    @WebResult(name = "CelsiusToFahrenheitResponse", targetNamespace = "http://example.com/temperature", partName = "parameters")
    public CelsiusToFahrenheitResponse celsiusToFahrenheit(

        @WebParam(partName = "parameters", name = "CelsiusToFahrenheitRequest", targetNamespace = "http://example.com/temperature")
        CelsiusToFahrenheitRequest parameters
    );
}
